# Site settings
title: "Notes of things I should remember, but don't"
email: "nkarani31@gmail.org"
baseurl: "/website"
twitter_username: nirav_karani
github_username:  neeravkarani

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  math_engine_opts:
    preview: true