# Site settings
title: "NK's blog"
email: "nkarani31@gmail.org"
description: "Notes of things I cannot remember."
twitter_username: nirav_karani
github_username:  neeravkarani

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  math_engine_opts:
    preview: true