# Site settings
title: "NK's blog"
description: "NK's blog"
email: "nkarani31@gmail.org"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  math_engine_opts:
    preview: true

theme: jekyll-theme-minimal
