# Site settings
title: NK's blog
email: 
description: "Notes of things I cannot remember."
baseurl: "website/"
url: "https://neeravkarani.github.io/website/"
twitter_username: nirav_karani
github_username:  neeravkarani

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge